apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  selector:
    matchLabels:
      app: cart
  replicas: 2
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart-container
          image: cart-app:1.0-SNAPSHOT
          ports:
            - name: http
              containerPort: 9080
            - name: hazelcast
              containerPort: 5701
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: superuser
            - name: POSTGRES_SERVER
              value: postgres-db-lb.default.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: sessionDb

---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: NodePort
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
      nodePort: 31000

---
#apiVersion: v1
#kind: Service
#metadata:
#  name: infinispan-embedded
#spec:
#  clusterIP: None
#  ports:
#    - name: discovery
#      port: 7800
#      protocol: TCP
#      targetPort: 7800
#  selector:
#    app: cart
#  sessionAffinity: None
#  type: ClusterIP
#status:
#  loadBalancer: { }

---
# PostgreSQL StatefulSet Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-lb
spec:
  selector:
    app: postgresql-db
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432

---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      # Official Postgres Container
      containers:
        - name: postgresql-db
          image: postgres:14.4-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          # Resource Limits
          resources:
            requests:
              memory: "265Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          # Data Volume
          volumeMounts:
            - name: postgresql-db-disk
              mountPath: ./postgres/var/pgdata
          env:
            - name: "POSTGRES_PASSWORD"
              value: "superuser"
            - name: "POSTGRES_DB"
              value: "sessionDb"
            - name: "POSTGRES_USER"
              value: "postgres"
  # Volume Claim
  volumeClaimTemplates:
    - metadata:
        name: postgresql-db-disk
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi