apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  selector:
    matchLabels:
      app: cart
  replicas: 3
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart-container
          image: cart-app:1.0-SNAPSHOT
          ports:
            - name: http
              containerPort: 9080
            - name: hazelcast
              containerPort: 5701
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: NodePort
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 9080
      targetPort: 9080
      nodePort: 31000

---
apiVersion: v1
kind: Service
metadata:
  name: infinispan-embedded
spec:
  clusterIP: None
  ports:
    - name: discovery
      port: 7800
      protocol: TCP
      targetPort: 7800
  selector:
    app: cart
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: { }
